### ISSUE TITLE
C2-12828-1 in v1.1

### ISSUE THREAD

**Issue by IlyaAstafev** [hatoving/zeldapicross_vita#3]
I am getting an error after opening the game (with data files):

`(C2-12828-1)`
`Saved Core File Succeeded.`
`ux0:data/psp2core-1663566082-0x00008c2d7d-eboot.bin.psp2dmp`

**Comment by Just4Link** [comment]
Same Problem here. Im on 3.60 followed vita.hacks.guide

**Comment by Gordyfan420** [comment]
I was able to solve it by making my own save folder at
ux0:data/ZeldaPicross/save

**Comment by IlyaAstafev** [comment]
> I was able to solve it by making my own save folder at
> ux0:data/ZeldaPicross/save

Oh-oh-oh, that's great! Thank you for help!
